### ISSUE TITLE
Incompatible with webpack

### ISSUE THREAD

**Issue by morgante** [davepacheco/node-jsprim#13] opened 2015-11-20 18:21 UTC
This module is unfortunately currently incompatible with webpack. It produces the following error when built in a webpack environment:
```
define cannot be used indirect
```

The underlying issue is actually with [json-schema](https://github.com/kriszyp/json-schema/issues/59), but because that module hasn't been updated since 2012 I might suggest choosing a different tool.

**Comment by jclulow** [comment] 2015-11-20 19:09
@morgante And what tool might you suggest?  As far as I can tell, `json-schema` still works just fine, _even though_ nobody has changed it in three years.

**Comment by morgante** [comment] 2015-11-20 19:27
[is-my-json-valid](https://github.com/mafintosh/is-my-json-valid) seems to be updated quite regularly, so it might be worth trying.

You're right that it does seem json-schema is still mostly working, so it might be worth considering a fork if the issue isn't addressed soon.

**Comment by Verikon** [comment] 2015-11-30 23:48
Plus 1 .

**Comment by bingomanatee** [comment] 2015-12-24 21:53
+ getting this issue as well.

**Comment by davepacheco** [comment] 2015-12-30 19:11
Because we use this validator in several latency-sensitive, internet-facing services, in order to switch implementations, we'd need to verify that there are no semantic changes (i.e., the new implementation rejects any invalid inputs rejected by the old implementation, and accepts valid inputs accepted by the old implementation) and no significant performance regressions (since existing implementations vary in latency by orders of magnitude).  At the very least, any semantic differences would need to be well-understood and documented for a major bump of this module.  We'd also need to normalize the reported errors to match the existing ones that this library emits.

It's a fair bit of work for someone to find a new implementation, integrate it into this module (translating errors), do the semantic testing, and do the performance testing.  If someone steps up to do that, we'd be happy to review the test results and take that PR, as long as it meets the above requirements.  

I'm sorry that the json-schema dependency is affecting people's ability to use this module with webpack, but I don't believe any of the current maintainers has the interest or time to do that work ourselves, especially to work around what sounds like a deficiency in webpack.

**Comment by ForsakenHarmony** [comment] 2016-09-12 20:17
you just have to bump the json-schema version

**Comment by davepacheco** [comment] 2016-09-13 00:08
Fixed in version 1.3.1.

**Closed by davepacheco** 2016-09-13 00:08 UTC
